# Generated by Django 2.2.4 on 2021-04-22 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_against', models.TextField(max_length=50)),
                ('score_for', models.IntegerField()),
                ('score_against', models.IntegerField()),
                ('date', models.DateField(default=None)),
                ('result', models.TextField(default=None, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.TextField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statname', models.TextField(max_length=100)),
                ('statval', models.IntegerField()),
                ('game_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Game')),
                ('season_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Season')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Season_Averages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.TextField(max_length=255)),
                ('stat_val', models.IntegerField()),
                ('season_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Season')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Team')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Team'),
        ),
        migrations.CreateModel(
            name='Game_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_scorers_txt', models.TextField(max_length=255)),
                ('con_scorers_txt', models.TextField(max_length=255)),
                ('pen_scorers_txt', models.TextField(max_length=255)),
                ('week_no', models.IntegerField()),
                ('game_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Game')),
                ('season_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Season')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='season_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Team'),
        ),
    ]
