# Generated by Django 2.2.4 on 2021-02-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamesid', models.IntegerField()),
                ('top_stat1_name', models.TextField(max_length=50)),
                ('top_stat2_name', models.TextField(max_length=50)),
                ('top_stat3_name', models.TextField(max_length=50)),
                ('top_stat4_name', models.TextField(max_length=50)),
                ('top_stat5_name', models.TextField(max_length=50)),
                ('top_stat6_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='season_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonid', models.IntegerField()),
                ('year', models.TextField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='team_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField(max_length=50)),
                ('teamid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stats_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statname', models.TextField(max_length=100)),
                ('statval', models.IntegerField()),
                ('gamesid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.games_table')),
                ('seasonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.season_table')),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.team_table')),
            ],
        ),
        migrations.AddField(
            model_name='season_table',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.team_table'),
        ),
        migrations.AddField(
            model_name='games_table',
            name='seasonid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.season_table'),
        ),
        migrations.AddField(
            model_name='games_table',
            name='teamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.team_table'),
        ),
    ]
