# Generated by Django 2.2.4 on 2021-02-05 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games_table',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
