# Generated by Django 2.2.4 on 2021-02-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_scorer', models.TextField(max_length=50)),
                ('con_scorer', models.TextField(max_length=50)),
                ('pen_scorer', models.TextField(max_length=50)),
                ('pen_attempts', models.IntegerField()),
                ('pen_made', models.IntegerField()),
                ('con_attempts', models.IntegerField()),
                ('con_made', models.IntegerField()),
                ('game_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Game')),
                ('season_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Season')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Team')),
            ],
        ),
    ]
