# Generated by Django 2.2.4 on 2021-02-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_game_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Events',
            new_name='Game_Event',
        ),
    ]
