# Generated by Django 2.2.4 on 2021-02-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20210216_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_event',
            old_name='con_scorer',
            new_name='game_event_scorer_name',
        ),
        migrations.RemoveField(
            model_name='game_event',
            name='con_attempts',
        ),
        migrations.RemoveField(
            model_name='game_event',
            name='con_made',
        ),
        migrations.RemoveField(
            model_name='game_event',
            name='pen_attempts',
        ),
        migrations.RemoveField(
            model_name='game_event',
            name='pen_made',
        ),
        migrations.RemoveField(
            model_name='game_event',
            name='pen_scorer',
        ),
        migrations.RemoveField(
            model_name='game_event',
            name='try_scorer',
        ),
        migrations.AddField(
            model_name='game_event',
            name='game_event_type',
            field=models.TextField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
