# Generated by Django 2.2.4 on 2021-02-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20210205_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='games_table',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='season_table',
            new_name='Season',
        ),
        migrations.RenameModel(
            old_name='stats_table',
            new_name='Stat',
        ),
        migrations.RenameModel(
            old_name='team_table',
            new_name='Team',
        ),
    ]
