# Generated by Django 2.2.4 on 2021-02-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20210205_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='seasonid',
            new_name='season_name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='teamid',
            new_name='team_name',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='teamid',
            new_name='team_name',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='gamesid',
            new_name='game_name',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='seasonid',
            new_name='season_name',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='teamid',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gamesid',
        ),
        migrations.RemoveField(
            model_name='season',
            name='seasonid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamid',
        ),
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='season_name',
            field=models.TextField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(),
        ),
    ]
