# Generated by Django 2.2.4 on 2021-02-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20210216_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_event',
            old_name='game_event_type',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='game_event',
            old_name='game_event_scorer_name',
            new_name='scorer_name',
        ),
        migrations.AddField(
            model_name='game_event',
            name='event_val',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
