# Generated by Django 2.2.4 on 2021-02-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_game_event_week_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='game_event',
            name='event_val',
        ),
        migrations.RemoveField(
            model_name='game_event',
            name='scorer_name',
        ),
        migrations.RemoveField(
            model_name='game_event',
            name='week_no',
        ),
        migrations.AddField(
            model_name='game_event',
            name='con_scorers_txt',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_event',
            name='pen_scorers_txt',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_event',
            name='try_scorers_txt',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
