# Generated by Django 2.2.4 on 2021-02-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20210216_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_event',
            name='week_no',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
