# Generated by Django 2.2.4 on 2021-02-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_game_event_week_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_Averages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.TextField(max_length=255)),
                ('stat_val', models.IntegerField()),
                ('season_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Season')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Team')),
            ],
        ),
    ]
