# Generated by Django 2.2.4 on 2021-03-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='footage',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
